export const QUOTES = [
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Talk is cheap. Show me the code.', author: 'Linus Torvalds' },
  { text: 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', author: 'Martin Fowler' },
  { text: 'Simplicity is prerequisite for reliability.', author: 'Edsger W. Dijkstra' },
  { text: 'The only way to learn a new programming language is to write programs in it.', author: 'Dennis Ritchie' },
  { text: 'There are only two kinds of languages: the ones people complain about and the ones nobody uses.', author: 'Bjarne Stroustrup' },
  { text: 'One of my most productive days was throwing away 1,000 lines of code.', author: 'Ken Thompson' },
  { text: 'Given enough eyeballs, all bugs are shallow.', author: 'Eric S. Raymond' },
  { text: 'The function of good software is to make the complex appear to be simple.', author: 'Grady Booch' },
  { text: 'Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', author: 'Bill Gates' },
  { text: 'Make it work, make it right, make it fast.', author: 'Kent Beck' },
  { text: 'Code is like humor. When you have to explain it, it’s bad.', author: 'Cory House' },
  { text: 'Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.', author: 'Antoine de Saint-Exupéry' },
  { text: 'The most dangerous phrase in the language is: We’ve always done it that way.', author: 'Grace Hopper' },
  { text: 'First, solve the problem. Then, write the code.', author: 'John Johnson' },
  { text: 'The computer was born to solve problems that did not exist before.', author: 'Bill Gates' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Science is what we understand well enough to explain to a computer. Art is everything else we do.', author: 'Donald Knuth' },
  { text: 'Premature optimization is the root of all evil.', author: 'Donald Knuth' },
  { text: 'Programs must be written for people to read, and only incidentally for machines to execute.', author: 'Harold Abelson' },
  { text: 'Bad programmers worry about the code. Good programmers worry about data structures and their relationships.', author: 'Linus Torvalds' },
  { text: 'There are two hard things in Computer Science: cache invalidation and naming things.', author: 'Phil Karlton' },
  { text: 'Software is like sex: it’s better when it’s free.', author: 'Linus Torvalds' },
  { text: 'Clean code always looks like it was written by someone who cares.', author: 'Robert C. Martin' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'It’s not a bug – it’s an undocumented feature.', author: 'Anonymous' },
  { text: 'The best error message is the one that never shows up.', author: 'Thomas Fuchs' },
  { text: 'Controlling complexity is the essence of computer programming.', author: 'Brian Kernighan' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'If you think cryptography is the solution to your security problem, then you don’t know what your problem is.', author: 'Gene Spafford' },
  { text: 'Programming isn’t about what you know; it’s about what you can figure out.', author: 'Chris Pine' },
  { text: 'Treating your users as co-developers is your least-hassle route to rapid code improvement.', author: 'Eric S. Raymond' },
  { text: 'The key to performance is elegance, not battalions of special cases.', author: 'Jon Bentley' },
  { text: 'No problem can be solved from the same level of consciousness that created it.', author: 'Albert Einstein' },
  { text: 'Testing shows the presence, not the absence of bugs.', author: 'Edsger W. Dijkstra' },
  { text: 'Before software can be reusable it first has to be usable.', author: 'Ralph Johnson' },
  { text: 'Good judgment comes from experience, and experience comes from bad judgment.', author: 'Frederick P. Brooks' },
  { text: 'Happiness depends upon ourselves.', author: 'Aristotle' },
  { text: 'The code you delete makes you a good programmer.', author: 'Mario Fusco' },
  { text: 'Elegance is not a dispensable luxury but a quality that decides between success and failure.', author: 'Edsger W. Dijkstra' },
  { text: 'Leadership is not about being in charge. It is about taking care of those in your charge.', author: 'Simon Sinek' },
  { text: 'Truth can only be found in one place: the code.', author: 'Robert C. Martin' },
  { text: 'We build our computer (systems) the way we build our cities: over time, without a plan, upon the ruins of the past.', author: 'Ellen Ullman' },
  { text: 'A mind that is stretched by a new experience can never go back to its old dimensions.', author: 'Oliver Wendell Holmes Jr.' },
  { text: 'Copying code from Stack Overflow is like using someone else’s toothbrush.', author: 'Anonymous' },
  { text: 'The most important skill for a developer is the ability to search effectively.', author: 'John Sonmez' },
  { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'The best way to predict the future is to invent it.', author: 'Alan Kay' },
  { text: 'Debugging is twice as hard as writing the code in the first place.', author: 'Brian Kernighan' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' }
];
